services:
  backend:
    build: ../backend
    ports:
      - "5000:5000"
    env_file:
      - ../backend/.env

  frontend:
    build: ../frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"

  # Test services
  backend-test:
    build:
      context: ../backend
      dockerfile: Dockerfile.test
    volumes:
      - ../backend:/app
    environment:
      - PYTHONPATH=/app
    command: pytest -v --cov=. tests/
    env_file:
      - ../backend/.env

  frontend-test:
    build:
      context: ../frontend
      dockerfile: Dockerfile.test
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command: npm test